# Generated by Django 3.2.7 on 2023-12-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ipv4addr', models.CharField(max_length=255, unique=True)),
                ('oem', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('asn', models.IntegerField(blank=True, null=True)),
                ('ipv4addr', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('connected_ports', models.CharField(max_length=255)),
                ('peering_policy', models.CharField(max_length=255)),
                ('speed', models.IntegerField()),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tshoot.switch')),
            ],
        ),
    ]
